# This is a basic workflow to help you get started with Actions

name: CI
- name: Rust Release binary
  # You may pin to the exact commit or the version.
  # uses: rust-build/rust-build.action@38ff85c862c183cece38087560e88828f08fe8a5
  uses: rust-build/rust-build.action@v1.3.2
  with:
    # Output target
    RUSTTARGET: 
    # List of extra files to include in build
    EXTRA_FILES: # optional
    # Path to directory containing Cargo.toml (defaults to project root)
    SRC_DIR: # optional
    # List of archive types to publish the binaries with, default "zip", supports zip and all tar formats
    ARCHIVE_TYPES: # optional
    # Full name of archive to upload (you must specify file extension and change this if building multiple targets)
    ARCHIVE_NAME: # optional
    # Relative path of script to run before building
    PRE_BUILD: # optional
    # Relative path of script to run after building
    POST_BUILD: # optional
    # If set to "true", the resulting binary will be stripped and compressed by UPX. ("false" by default)
    MINIFY: # optional
    # The rust toolchain version to use (see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification)
    TOOLCHAIN_VERSION: # optional
    # What method to use to upload compiled binaries, supported values: (release, none), default: release
    UPLOAD_MODE: # optional
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
